site_name: Test Docs
repo_url: https://github.com/Greater-Wellington-Regional-Council/gw-dagster
site_url: https://Greater-Wellington-Regional.github.io/gw-dagster
site_description: This is a [Dagster](https://dagster.io/) project for GWRC.
edit_uri: edit/main/docs/
repo_name: Greater-Wellington-Regional-Council/gw-dagster

nav:
  - Home: README.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            heading_level: 3
            show_root_full_path: false
            members: false
            group_by_category: true
            show_category_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/auth-buttons.js
